<Project>
    <PropertyGroup>
        <!-- Code Quality & Analysis -->
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisMode>Recommended</AnalysisMode>
    </PropertyGroup>

    <PropertyGroup Condition="'$(ContinuousIntegrationBuild)' == 'true'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup>
        <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1605;NU1701</WarningsNotAsErrors>
    </PropertyGroup>
</Project>